"use client";

import { useEffect, useState } from "react";
const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
export default function Home() {
  const [projects,setProjects]=useState([]),[projectId,setProjectId]=useState(""),[project,setProject]=useState(null),[relationships,setRelationships]=useState([]),[timeline,setTimeline]=useState([]),[name,setName]=useState(""),[description,setDescription]=useState(""),[episodeTitle,setEpisodeTitle]=useState(""),[episodeContent,setEpisodeContent]=useState(""),[file,setFile]=useState(null),[mediaFile,setMediaFile]=useState(null),[tab,setTab]=useState("overview"),[loading,setLoading]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[job,setJob]=useState(null),[transcript,setTranscript]=useState(null),[reviewScript,setReviewScript]=useState(null),[style,setStyle]=useState("youtube");
  async function request(path,options={}){const res=await fetch(`${API}${path}`,options);const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.detail||"API request failed");return data;}
  async function loadProjects(){try{const data=await request("/api/v1/projects");setProjects(data);if(!projectId&&data[0])setProjectId(data[0].id);}catch(e){setError(e.message);}}
  async function loadProject(id=projectId){if(!id)return;try{const [data,rels,time]=await Promise.all([request(`/api/v1/projects/${id}`),request(`/api/v1/projects/${id}/relationships`),request(`/api/v1/projects/${id}/timeline`)]);setProject(data);setRelationships(rels);setTimeline(time);}catch(e){setError(e.message);}}
  useEffect(()=>{loadProjects();},[]);useEffect(()=>{loadProject();},[projectId]);
  useEffect(()=>{if(!job?.id||["completed","failed"].includes(job.status))return;const t=setInterval(async()=>{try{const current=await request(`/api/v1/jobs/${job.id}`);setJob(current);if(current.status==="completed"){await loadProject();setMessage("Job hoàn tất.");}if(current.status==="failed")setError(current.error||"Job xử lý thất bại");}catch(e){setError(e.message);}},1500);return()=>clearInterval(t);},[job?.id,job?.status,projectId]);
  async function createProject(){if(!name.trim())return;setLoading(true);try{const c=await request("/api/v1/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,description})});setName("");setDescription("");setProjectId(c.id);await loadProjects();await loadProject(c.id);setMessage("Đã tạo project.");}catch(e){setError(e.message);}finally{setLoading(false);}}
  async function createEpisode(){if(!projectId||!episodeTitle.trim())return;setLoading(true);try{await request(`/api/v1/projects/${projectId}/episodes`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:episodeTitle,content:episodeContent,source_type:"text"})});setEpisodeTitle("");setEpisodeContent("");await loadProject();setMessage("Đã tạo episode.");}catch(e){setError(e.message);}finally{setLoading(false);}}
  async function uploadEpisode(){if(!projectId||!file)return;setLoading(true);try{const f=new FormData();f.append("file",file);if(episodeTitle.trim())f.append("title",episodeTitle.trim());const d=await request(`/api/v1/projects/${projectId}/episodes/upload`,{method:"POST",body:f});setFile(null);setEpisodeTitle("");await loadProject();setJob(d.job);setMessage("Đã nhận tài liệu. OCR + AI đang chạy.");setTab("episodes");}catch(e){setError(e.message);}finally{setLoading(false);}}
  async function uploadMedia(){if(!projectId||!mediaFile)return;setLoading(true);try{const f=new FormData();f.append("file",mediaFile);if(episodeTitle.trim())f.append("title",episodeTitle.trim());const d=await request(`/api/v1/projects/${projectId}/episodes/media`,{method:"POST",body:f});setMediaFile(null);setEpisodeTitle("");await loadProject();setJob(d.job);setMessage("Đã nhận media. FFmpeg + STT + AI đang chạy.");setTab("episodes");}catch(e){setError(e.message);}finally{setLoading(false);}}
  async function analyzeEpisode(id){setLoading(true);try{const d=await request(`/api/v1/projects/${projectId}/episodes/${id}/analyze`,{method:"POST"});setJob(d.job);setMessage("Đã đưa episode vào hàng đợi AI.");}catch(e){setError(e.message);}finally{setLoading(false);}}
  async function loadTranscript(id){try{const d=await request(`/api/v1/projects/${projectId}/episodes/${id}/transcript`);setTranscript({...d,episodeId:id});setTab("transcript");}catch(e){setError(e.message);}}
  async function createReviewScript(id){setLoading(true);setError("");try{const f=new FormData();f.append("style",style);const d=await request(`/api/v1/projects/${projectId}/episodes/${id}/review-script`,{method:"POST",body:f});setJob(d.job);setMessage("Đã đưa Review Script vào hàng đợi AI.");}catch(e){setError(e.message);}finally{setLoading(false);}}
  async function loadReviewScript(id){try{const d=await request(`/api/v1/projects/${projectId}/episodes/${id}/transcript`);const rs=d.transcript?.review_script; if(rs){setReviewScript(rs);setTab("review-script");}else setError("Review Script chưa có");}catch(e){setError(e.message);}}
  function downloadSrt(id){window.open(`${API}/api/v1/projects/${projectId}/episodes/${id}/srt`,"_blank");}
  const characters=project?.characters||[],events=project?.events||[],episodes=project?.episodes||[];const tabs=[["overview","Tổng quan"],["episodes","Episodes"],["characters","Nhân vật"],["events","Sự kiện"],["relationships","Quan hệ"],["timeline","Timeline"],["transcript","Transcript"],["review-script","Review Script"]];
  return <main style={styles.page}><header style={styles.header}><div><p style={styles.eyebrow}>AI CONTENT REVIEW</p><h1 style={styles.h1}>Project Knowledge</h1><p style={styles.subtitle}>OCR → Queue → FFmpeg → STT → AI → Review Script</p></div><button onClick={()=>loadProject()} style={styles.refresh}>↻ Làm mới</button></header>
  <section style={styles.topGrid}><div style={styles.card}><label style={styles.label}>Project</label><select value={projectId} onChange={e=>setProjectId(e.target.value)} style={styles.input}><option value="">Chọn project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div style={styles.card}><strong>{project?.name||"Chưa chọn project"}</strong><p style={styles.muted}>{project?.description||"Tạo project để bắt đầu."}</p><div style={styles.stats}><span>{episodes.length} Episodes</span><span>{characters.length} Characters</span><span>{events.length} Events</span><span>{relationships.length} Relations</span></div></div></section>
  {job&&<section style={styles.job}><strong>Job: {job.status}</strong><span>{job.attempts||0}/{job.max_attempts||3} attempts</span>{job.error&&<small>{job.error}</small>}</section>}<section style={styles.tabs}>{tabs.map(([k,l])=><button key={k} onClick={()=>setTab(k)} style={tab===k?styles.activeTab:styles.tab}>{l}</button>)}</section>{message&&<div style={styles.success}>{message}</div>}{error&&<div style={styles.error}>{error}</div>}
  {tab==="overview"&&<section style={styles.grid}><div style={styles.card}><h2>Tạo project</h2><input value={name} onChange={e=>setName(e.target.value)} placeholder="Tên series / nội dung" style={styles.input}/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Mô tả" rows={4} style={styles.textarea}/><button disabled={loading} onClick={createProject} style={styles.button}>Tạo project</button></div><div style={styles.card}><h2>Nhập episode</h2><input value={episodeTitle} onChange={e=>setEpisodeTitle(e.target.value)} placeholder="Tên chương / tập" style={styles.input}/><textarea value={episodeContent} onChange={e=>setEpisodeContent(e.target.value)} placeholder="Nội dung episode..." rows={5} style={styles.textarea}/><button disabled={loading||!projectId||!episodeContent.trim()} onClick={createEpisode} style={styles.button}>Thêm text episode</button><hr style={styles.hr}/><input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.bmp,.tiff" onChange={e=>setFile(e.target.files?.[0]||null)} style={styles.input}/><button disabled={loading||!projectId||!file} onClick={uploadEpisode} style={styles.button}>Upload PDF / ảnh → OCR + AI</button><hr style={styles.hr}/><input type="file" accept="video/*,audio/*,.mkv,.avi,.m4v,.flac,.ogg" onChange={e=>setMediaFile(e.target.files?.[0]||null)} style={styles.input}/><button disabled={loading||!projectId||!mediaFile} onClick={uploadMedia} style={styles.button}>Upload Video / Audio → STT + AI</button><p style={styles.muted}>Media tối đa 1 GB · transcript timestamp · SRT · review script.</p></div></section>}
  {tab==="episodes"&&<section style={styles.card}><h2>Episodes</h2>{!episodes.length?<p style={styles.muted}>Chưa có episode.</p>:episodes.map((e,i)=><div key={e.id} style={styles.row}><div><strong>#{i+1} · {e.title}</strong><p style={styles.muted}>{e.source_type}{e.source_filename?` · ${e.source_filename}`:""}</p></div><div style={styles.actions}><button onClick={()=>loadTranscript(e.id)} style={styles.smallButton}>Transcript</button><button onClick={()=>downloadSrt(e.id)} style={styles.smallButton}>SRT</button><button onClick={()=>createReviewScript(e.id)} disabled={loading||e.source_type==="text"} style={styles.smallButton}>Tạo Review Script</button><button onClick={()=>loadReviewScript(e.id)} style={styles.smallButton}>Xem Script</button><button onClick={()=>analyzeEpisode(e.id)} disabled={loading||!e.content} style={styles.smallButton}>Phân tích AI</button></div></div>)}</section>}
  {tab==="transcript"&&<section style={styles.card}><h2>Timestamp Transcript</h2>{!transcript?<p style={styles.muted}>Chọn Transcript từ episode media.</p>:<><div style={styles.transcriptHeader}><strong>{transcript.title}</strong><button onClick={()=>downloadSrt(transcript.episodeId)} style={styles.smallButton}>Mở SRT</button></div><div style={styles.transcript}>{(transcript.transcript.segments||[]).map(s=><div key={s.index} style={styles.segment}><span style={styles.time}>{formatTime(s.start)} → {formatTime(s.end)}</span><span>{s.text}</span></div>)}</div></>}</section>}
  {tab==="review-script"&&<section style={styles.card}><h2>AI Review Script</h2><select value={style} onChange={e=>setStyle(e.target.value)} style={styles.input}><option value="youtube">YouTube Review</option><option value="shorts">TikTok / Shorts</option><option value="documentary">Documentary</option></select>{!reviewScript?<p style={styles.muted}>Chọn “Xem Script” sau khi job hoàn tất.</p>:<><h3>{reviewScript.hook}</h3><p>{reviewScript.intro}</p>{(reviewScript.segments||[]).map((s,i)=><div key={i} style={styles.knowledge}><small>{formatTime(s.start)} → {formatTime(s.end)}</small><strong>{s.script}</strong><span>Evidence: {s.evidence}</span></div>)}<p><strong>{reviewScript.outro}</strong></p></>}</section>}
  {tab==="characters"&&<section style={styles.card}><h2>Characters</h2>{!characters.length?<p style={styles.muted}>Chưa có nhân vật.</p>:<div style={styles.list}>{characters.map(c=><div key={c.id} style={styles.knowledge}><strong>{c.name}</strong><span>{c.role||"Chưa xác định vai trò"}</span></div>)}</div>}</section>}{tab==="events"&&<section style={styles.card}><h2>Events</h2>{!events.length?<p style={styles.muted}>Chưa có sự kiện.</p>:events.map(e=><div key={e.id} style={styles.knowledge}><strong>{e.title}</strong><span>{episodes.find(x=>x.id===e.episode_id)?.title||"Không xác định"}</span></div>)}</section>}{tab==="relationships"&&<section style={styles.card}><h2>Character Relationships</h2>{relationships.map(r=><div key={r.id} style={styles.knowledge}><strong>{r.from} → {r.to}</strong><span>{r.relation}</span></div>)}</section>}{tab==="timeline"&&<section style={styles.card}><h2>Series Timeline</h2>{timeline.map((x,i)=><div key={x.episode_id} style={styles.timelineItem}><b>{i+1}. {x.episode_title}</b>{x.events?.map(ev=><div key={ev.id} style={styles.eventLine}>{ev.title}</div>)}</div>)}</section>}
  <footer style={styles.footer}>API: {API} · Redis Queue · FFmpeg · STT · SRT · AI Review Script · PostgreSQL</footer></main>;
}
function formatTime(seconds){const ms=Math.max(0,Math.round(Number(seconds||0)*1000));const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000),x=ms%1000;return `${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}.${String(x).padStart(3,"0")}`;}
const styles={page:{maxWidth:1240,margin:"0 auto",padding:32,fontFamily:"Arial,sans-serif",color:"#171717"},header:{display:"flex",justifyContent:"space-between",alignItems:"flex-end",marginBottom:24},eyebrow:{margin:0,fontSize:12,fontWeight:700,letterSpacing:2,color:"#666"},h1:{fontSize:38,margin:"8px 0"},subtitle:{color:"#666",margin:0},topGrid:{display:"grid",gridTemplateColumns:"1fr 2fr",gap:16,marginBottom:18},grid:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:18},card:{border:"1px solid #ddd",borderRadius:14,padding:22,background:"#fff"},job:{display:"flex",gap:18,alignItems:"center",padding:12,border:"1px solid #ddd",borderRadius:10,marginBottom:14,background:"#fafafa"},tabs:{display:"flex",flexWrap:"wrap",gap:8,margin:"18px 0",borderBottom:"1px solid #ddd",paddingBottom:8},tab:{border:0,background:"transparent",padding:"10px 14px",cursor:"pointer",color:"#666"},activeTab:{border:0,borderBottom:"2px solid #111",background:"transparent",padding:"10px 14px",cursor:"pointer",fontWeight:700},label:{display:"block",fontWeight:700,marginBottom:8},input:{width:"100%",boxSizing:"border-box",padding:12,border:"1px solid #ccc",borderRadius:8,background:"#fff",marginBottom:12},textarea:{width:"100%",boxSizing:"border-box",padding:12,border:"1px solid #ccc",borderRadius:8,resize:"vertical",fontFamily:"inherit",marginBottom:12},button:{padding:"11px 16px",border:0,borderRadius:8,cursor:"pointer",fontWeight:700},smallButton:{padding:"9px 12px",border:"1px solid #ccc",borderRadius:8,background:"#fff",cursor:"pointer"},refresh:{padding:"9px 12px",border:"1px solid #ccc",borderRadius:8,background:"#fff",cursor:"pointer"},stats:{display:"flex",flexWrap:"wrap",gap:18,color:"#555",fontSize:14},row:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,padding:"14px 0",borderBottom:"1px solid #eee"},actions:{display:"flex",gap:8,flexWrap:"wrap"},list:{display:"grid",gap:10},knowledge:{display:"grid",gap:5,padding:15,border:"1px solid #eee",borderRadius:10,background:"#fafafa"},transcriptHeader:{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14},transcript:{display:"grid",gap:6},segment:{display:"grid",gridTemplateColumns:"190px 1fr",gap:16,padding:"10px 12px",borderBottom:"1px solid #eee"},time:{fontFamily:"monospace",color:"#666"},timelineItem:{padding:"12px 0",borderBottom:"1px solid #eee"},eventLine:{marginTop:8,padding:8,background:"#fafafa"},muted:{color:"#777"},hr:{border:0,borderTop:"1px solid #eee",margin:"18px 0"},success:{padding:12,borderRadius:8,background:"#eef7ee",marginBottom:14},error:{padding:12,borderRadius:8,background:"#fff0f0",marginBottom:14},footer:{marginTop:30,paddingTop:18,borderTop:"1px solid #eee",fontSize:12,color:"#888"}};
